name: jcmsk
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cmake=3.22.1
  - itk=5.2.0
  - itkwidgets=0.32.0
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.17.0
  - jupyterlab=3.4.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.14.0
  - jupyterlab_widgets=1.1.0
  - matplotlib=3.1.2
  - matplotlib-inline=0.1.2
  - nbclassic=0.3.5
  - nbclient=0.6.4
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - notebook=6.4.12
  - numpy=1.22.3
  - numpy-base=1.22.3
  - pandas=1.4.2
  - pillow=9.0.1
  - pip=22.1.2
  - pydicom=2.3.0
  - python=3.8.10
  - pyvista=0.34.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.1.0
  - qt=5.9.7
  - scikit-image=0.19.3
  - scipy=1.7.3
  - simpleitk=2.0.2
  - vtk=9.0.3
  - pip:
    - itk-core==5.2.0
    - itk-filtering==5.2.0
    - itk-numerics==5.2.0
    - itk-registration==5.2.0
    - itk-segmentation==5.2.0
